name: Compile Resume

on: 
  push:
  workflow_dispatch:
    inputs:
      upload:
        description: "Upload resume as an artifact, even when it hasn't changed"
        default: true
        required: false
        type: boolean
      release_tag:
        description: 'Optionally release tag. If specified, a release will be created with the specified tag.'
        required: false
        type: string

permissions:
  contents: write
  actions: write
  pull-requests: write

jobs:
  resume:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
    - name: Check for resume changes
      if: github.ref == 'refs/heads/main'
      id: check_resume
      uses: tj-actions/changed-files@v46
      with:
        files: kleinsasser_resume.tex
    - name: Compile LaTeX
      if: steps.check_resume.outputs.any_changed == 'true' || github.event.inputs.upload
      uses: xu-cheng/latex-action@v4
      with:
        root_file: kleinsasser_resume.tex
        extra_system_packages: pandoc
        post_compile: pandoc --from=latex --to=plain kleinsasser_resume.tex -o kleinsasser_resume.txt
    - name: Upload Resume
      if: steps.check_resume.outputs.any_changed == 'true' || github.event.inputs.upload
      uses: actions/upload-artifact@v4
      with:
        name: Latest Resume
        path: |
          kleinsasser_resume.pdf
          kleinsasser_resume.txt
    - name: Bump version and push tag
      if: (steps.check_resume.outputs.any_changed == 'true' && github.ref == 'refs/heads/main') || github.event.inputs.release_tag != ''
      id: tag_version
      uses: mathieudutour/github-tag-action@v6.2
      with:
        custom_tag: ${{ github.event.inputs.release_tag }} # override autogenerated tag if specified on a manual run
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Create GitHub Release
      if: (steps.check_resume.outputs.any_changed == 'true' && github.ref == 'refs/heads/main') || github.event.inputs.release_tag != ''
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.tag_version.outputs.new_tag }}
        body: ${{ steps.tag_version.outputs.changelog }}
        files: |
          kleinsasser_resume.pdf
          kleinsasser_resume.txt
        generate_release_notes: false